# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043a168a5bcdb2767515426124327338842b73d4f094c7da1c2f9fcefc08474f06cf07773f9f94711368150339784b40c8e5313b25302922cb20eccd98a04c43

test:
  secret_key_base: 012f48aa6ce325fe03915d3209ec4759b08571bf1b8b1a4aece2e0923d82d78144c5d9f1c3219cc75199f4f94fa643f8fbf1765cac546f9c00819479ee06b937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
